Zz897426182/GoSunBigData

Collect/src/main/java/com/hzgc/collect/FTP.java, Collect/src/main/java/com/hzgc/collect/expand/conf/CommonConf.java, Collect/src/main/java/com/hzgc/collect/expand/log/AbstractLogWrite.java, Collect/src/main/java/com/hzgc/collect/expand/log/DataProcessLogWriter.java, Collect/src/main/java/com/hzgc/collect/expand/log/LogEvent.java, Collect/src/main/java/com/hzgc/collect/expand/merge/FileFactory.java, Collect/src/main/java/com/hzgc/collect/expand/merge/GetFaceObject.java, Collect/src/main/java/com/hzgc/collect/expand/merge/MergeSendCallback.java, Collect/src/main/java/com/hzgc/collect/expand/merge/MergeUtil.java, Collect/src/main/java/com/hzgc/collect/expand/merge/RecoverErrProDataThread.java, Collect/src/main/java/com/hzgc/collect/expand/merge/RecoverNotProData.java, Collect/src/main/java/com/hzgc/collect/expand/merge/RowsListFactory.java, Collect/src/main/java/com/hzgc/collect/expand/processer/ProcessCallBack.java, Collect/src/main/java/com/hzgc/collect/expand/processer/ProcessThread.java, Collect/src/main/java/com/hzgc/collect/expand/receiver/ReceiverImpl.java, Collect/src/main/java/com/hzgc/collect/expand/receiver/ReceiverScheduler.java, Collect/src/main/java/com/hzgc/collect/expand/util/ClusterOverFtpProperHelper.java, Collect/src/main/java/com/hzgc/collect/expand/util/FTPAddressProperHelper.java, Collect/src/main/java/com/hzgc/collect/expand/util/HelperFactory.java, Collect/src/main/java/com/hzgc/collect/expand/util/KafkaProperHelper.java, Collect/src/main/java/com/hzgc/collect/expand/util/ProducerKafka.java, Collect/src/main/java/com/hzgc/collect/expand/util/ProducerOverFtpProperHelper.java, Collect/src/main/java/com/hzgc/collect/expand/util/RocketMQProperHelper.java
修改人：刘思阳
修改内容：FTP模块添加序列化
修改模块：collect
合入人：赵喆
合入时间：2018-4-8
合入分支：master
=> FTP模块添加序列化

Common/src/main/java/com/hzgc/common/file/FileUtil.java, Common/src/main/java/com/hzgc/common/ftp/FTPDownloadUtils.java, Common/src/main/java/com/hzgc/common/ftp/FtpUtils.java, Common/src/main/java/com/hzgc/common/object/ObjectUtil.java
修改人：闫森
修改内容：common模块重新刷新
修改模块：common
合入人：赵喆
合入时间:2017/4/8
合入分支：master
=> Common模块重刷

Common/Common-service/src/main/java/com/hzgc/common/service/BigDataPath.java, Service/Face/pom.xml, Service/pom.xml
=> add BigDataPath.java

Service/Device/src/main/java/com/hzgc/service/device/controller/DeviceController.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/controller/ObjectInfoHandlerController.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/object/GroupByPkey.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/object/ObjectSearchResult.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/object/PSearchArgsModel.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/object/PersonObject.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/object/PersonSingleResult.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/object/SearchRecordOpts.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/object/SubQueryOpts.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/vo/ObjectInfoHandlerVO.java
修改人： 闫森
修改内容：staRepo库添加swagger
修改模块：service/staRepo。
合入人：赵喆
合入时间：2018-04-26
合入分支：master
=> staRepo添加swagger

Service/Device/src/main/java/com/hzgc/service/device/dao/HBaseDao.java, Service/Device/src/main/java/com/hzgc/service/device/service/WarnRuleService.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/dao/PhoenixDao.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/service/ObjectInfoHandlerService.java
修改人： 闫森
修改内容： starepo 代码修改
修改模块：starepo
合入人：赵喆
合入时间：2018-05-5
合入分支：master
=> 'starepo代码修改'

Distribution/bin/config-projectconf.sh, Distribution/bin/config-service.sh, Distribution/src/resources/project-conf.properties, Service/Alarm/bin/start-alarm.sh, Service/Device/bin/start-device.sh, Service/Dispatch/bin/start-dispatch.sh, Service/Dispatch/bin/stop-dispatch.sh, Service/StaRepo/bin/start-starepo.sh, Service/Visual/bin/start-visual.sh
修改人：陈柯
修改内容：将dispatch模块脚本添加上以及将service模块下的各个组件根据需求分发
修改模块：service
合入人：赵喆
合入时间：2018-06-01
合入分支：master
=> 将service模块下的各个组件根据需求分发

Cluster/Spark/bin/config-clusterconf.sh
修改人：陈柯
修改内容：新增修改sparkJob配置文件中的es的配置
修改模块：cluster
合入人：赵喆
合入时间：2018-06-06
合入分支：master
=> 新增修改sparkJob配置文件中的es的配置

Cluster/Spark/src/main/java/com/hzgc/cluster/spark/consumer/PutDataToEs.java, Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/alarm/FaceAddAlarmJob.scala, Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/alarm/FaceOffLineAlarmJob.scala, Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/alarm/FaceRecognizeAlarmJob.scala, Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/consumer/KafkaToParquet.scala
修改人： 伍家琦
修改内容：修改告警和抓拍保存，使用spark集成elasticsearch
修改模块：cluster/spark
合入人：赵喆
合入时间：2018-06-14
合入分支：alarm
=> 修改告警和抓拍保存，使用spark集成elasticsearch

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/dao/HBaseDao.java
修改人：闫森
问题单回归：规则名称去重
修改模块：dispatch
合入人：赵喆
合入时间：2018-06-25
合入分支：master
=> Bug修复：规则名称去重

Service/StaRepo/src/main/java/com/hzgc/service/starepo/bean/param/ObjectTypeParam.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/config/ResourceServerConfig.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/controller/ObjectInfoHandlerController.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/dao/PhoenixDao.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/service/ObjectInfoHandlerService.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/service/ObjectTypeService.java, Service/StaRepo/src/main/java/com/hzgc/service/starepo/service/ParseByOption.java, Service/Util/src/main/java/com/hzgc/service/util/api/service/DeviceQueryService.java, Service/Util/src/main/java/com/hzgc/service/util/rest/BigDataPath.java, Service/Visual/src/main/java/com/hzgc/service/visual/bean/CaptureCountSixHour.java
=>  Bug 906 905 904 888 885

Cluster/Spark/src/main/resources/sparkJob.properties, Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/clustering/KMeansClustering.scala
修改人：陈柯
修改内容：因平台mysql数据库升级，聚类中的表名发生更改所做出的调整
修改模块：cluster
合入人：赵喆
合入时间：2018-06-27
合入分支：master
=> 因平台mysql数据库升级，聚类中的表名发生更改所做出的调整

Service/StaRepo/src/main/java/com/hzgc/service/starepo/service/ParseByOption.java
修改人： 刘思阳
修改内容： 搜图时不传重点关注字段时，需要将重点关注人员放在结果集最前面
修改模块：visual
合入人：赵喆
合入时间：2018-06-27
合入分支：master
=> modif search object info

Cluster/Spark/bin/start-face-add-alarm-job.sh, Cluster/Spark/bin/start-face-offline-alarm-job.sh, Cluster/Spark/bin/start-face-recognize-alarm-job.sh, Cluster/Spark/bin/start-kafka-to-parquet.sh, Cluster/Spark/bin/start-kmeans-clustering-job.sh, Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/alarm/FaceOffLineAlarmJob.scala
修改人：雷禄辉
修改内容：修改spark 运行脚本
修改模块：cluster
合入人：赵喆
合入时间：2018-07-05
合入分支：2.3.0
=> Spark 运行脚本修改

Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/alarm/FaceAlarmJob.scala
修改人：陈柯
修改内容：修改合并告警类中PutToEs的声明
修改模块：spark
合入人：赵喆
合入时间：2018-07-13
合入分支：master
=> 修改合并告警类中puttoes的声明

Service/Clustering/src/main/java/com/hzgc/dubbo/clustering/ClusteringAttribute.java
修改人：赵喆
修改内容：增加因dubbo影响的clusteringAttribute类
修改模块：clustering
合入人：赵喆
合入时间：2018-07-14
合入分支：master
=> 增加因dubbo影响的clusteringAttribute类

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/controller/WarnRuleController.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/dao/HBaseDao.java
修改人:闫森
修改内容:修改设备名称实时查询
修改模块:dispatch
合入人:赵喆
合入时间:2018-07-24
合入分支:2.3.0
=> 去掉dispatch模块的设备名称

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/bean/Device.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/controller/WarnRuleController.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/dao/HBaseDao.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/WarnRuleService.java
修改人:闫森
修改内容:动态删除没有设备的ipcid
修改模块;dispatch
合入人:赵喆
合入时间:2018-07-27
合入分支:2.3.0
=> 动态删除没有设备的ipcid

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/dao/HBaseDao.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/WarnRuleService.java
修改人:闫森
修改内容:dispatch修改动态获取ipc
修改模块;dispatch
合入人:赵喆
合入时间:2018-07-28
合入分支:2.3.0
=> 修改dispatch

Service/Dispatch/pom.xml, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/bean/Device.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/WarnRuleService.java
修改人:闫森
修改内容;dispatch增加动态获取对象类型名称和ipcid
修改模块:dispatch
合入人:赵喆
合入时间:2018-07-31
合入分支:master
=> dispatch模块添加动态获取

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/controller/WarnRuleController.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/WarnRuleService.java
修改人:闫森
修改内容:增加添加规则进行ipcid是否存在进行判断
修改模块:dispatch
合入人:赵喆
合入时间:2018-08-01
合入分支:2.3.0
=> 增加添加规则ipcid判断

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/controller/WarnRuleController.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/WarnRuleService.java
修改人:闫森
修改内容:增加规则判断ipcid是否存在
修改模块;dispatch
合入人:赵喆
合入时间:2018-08-01
合入分支:master
=> 增加规则判断ipcid

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/controller/WarnRuleController.java
修改人:闫森
修改内容:修改规则添加ipcid
修改模块;dispatch
合入人:赵喆
合入时间:2018-08-09
合入分支;master
=> dispatch代码修改

Service/Clustering/src/main/java/com/hzgc/service/clustering/service/ClusteringSearchService.java
修改人：雷禄辉
修改内容：迁入人口查询接口修改bug
修改模块：Clustering
合入人：赵喆
合入时间：2018-08-13
合入分支：master
=> 迁入人口查询接口修改bug

Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/clustering/KMeansClustering.scala
修改人：雷禄辉
修改内容：kmeans修改字段bug
修改模块：Spark
合入人：赵喆
合入时间：2018-08-15
合入分支：master
=> kmeans修改字段bug

Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/alarm/FaceAlarmJob.scala
修改人：陈柯
修改内容：修改因大华相机路径变动的大图截取方式
修改模块：spark
合入人：赵喆
合入时间：2018-08-16
合入分支：master
=> 修改因大华相机路径变动的大图截取方式

Service/Clustering/src/main/java/com/hzgc/service/clustering/controller/ClusteringController.java, Service/Clustering/src/main/java/com/hzgc/service/clustering/service/ClusteringSearchService.java
修改人：雷禄辉
修改内容：迁入人口查询分页bug
修改模块：Clustering
合入人：赵喆
合入时间：2018-08-17
合入分支：master
=> 迁入人口查询分页bug

Service/PeopleManager/src/main/java/com/hzgc/service/clustering/controller/ResidentController.java, Service/PeopleManager/src/main/java/com/hzgc/service/clustering/dao/PhoenixDao.java, Service/PeopleManager/src/main/java/com/hzgc/service/clustering/service/ScheduledService.java
修改人：陈柯
修改内容：修复保存规则中的bug并删除一些不必要的log
修改模块：peoplemanager
合入人：赵喆
合入时间：2018-08-28
合入分支：master
=> 修复保存规则中的bug并删除一些不必要的log

Service/Fusion/bin/start-fusion.sh, Service/Fusion/bin/stop-fusion.sh, Service/Fusion/pom.xml, Service/Fusion/src/main/resources/application-dev.properties, Service/Fusion/src/main/resources/application-pro.properties
修改人：陈柯
修改内容：添加数据融合模块启停脚本
修改模块：Service模块
合入人：赵喆
合入时间：2018-09-19
合入分支：master
=> 添加数据融合模块启停脚本

Deployment/install/local/bin/componentInstall_local.sh, Deployment/install/local/env/offIptables_local.sh, Deployment/install/local/install/mysql_local.sh, Deployment/install/normal/haproxyInstall.sh, Deployment/install/normal/installCompent.sh, Deployment/install/normal/mysqlInstall.sh, Deployment/install/normal/offIptables.sh, Deployment/project/bin/project-deploy.sh, Distribution/src/assembly/assembly.xml
修改人：张宝霖
修改内容：脚本适配centos7
合入人：赵喆
合入时间：2018-09-27
合入分支：master
=>  脚本适配centos7

Cluster/Azkaban/bin/create-schedule-job-to-zip.sh, Deployment/project/bin/create-elasticsearch-index.sh, Deployment/project/bin/create-hbase-table.sh, Deployment/project/bin/gosunlib-deploy.sh, Deployment/project/sql/elasticsearch.sh
修改人：陈柯
修改内容：修改项目脚本以及azkaban打包删除一些没必要的脚本打包
合入人：赵喆
合入时间：2018-09-30
合入分支：master
=> 修改项目脚本以及azkaban打包删除一些没必要的脚本打包

Cluster/Azkaban/bin/24hour_count_table.sh, Cluster/Azkaban/bin/create-schedule-job-to-zip.sh, Cluster/Azkaban/bin/imsi_blacklist_table.sh, Cluster/Azkaban/bin/newpeople_table.sh, Cluster/Azkaban/bin/outpeople_table.sh, Cluster/Spark/bin/schema-merge-parquet-file.sh, Deployment/project/bin/project-deploy.sh
修改人：张宝霖
修改内容：peoplemanager部署，azkaban工作流
合入人：赵喆
合入时间：2018-10-10
合入分支：master
=> 增加peoplemanager部署，修改azkaban工作流

Cluster/Spark/src/main/resources/sparkJob.properties, Cluster/Spark/src/main/scala/com/hzgc/cluster/spark/consumer/KafkaToTidb.scala, Deployment/project/bin/create-kafka-topic.sh, Deployment/project/bin/project-deploy.sh, Service/Fusion/src/main/java/com/hzgc/service/fusion/model/FusionImsi.java, Service/Fusion/src/main/java/com/hzgc/service/fusion/service/Fusion.java, Service/Fusion/src/main/resources/mapping/FusionImsiMapper.xml
修改人：陈柯
修改内容：添加KafkaToTidb的参数配置
修改模块：spark
合入人：赵喆
合入时间：2018-10-09
合入分支：master
=> 添加KafkaToTidb的参数配置

Deployment/install/local/install/kafka_local.sh, Deployment/install/normal/kafkaInstall.sh, Deployment/project/bin/create-kafka-topic.sh, Deployment/project/bin/project-deploy.sh
修改人：张宝霖
修改内容：修改FaceCompare部署脚本
合入人：赵喆
合入时间：2018-10-15
合入分支：master
=> 修改FaceCompare部署脚本

Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/ConsumerFunction.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/DispatchApplication.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/cache/CaptureCache.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/cache/TableCache.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/compare/FaceCompare.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/compare/MacCompare.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/consumer/KafkaComsumer.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/dao/DispachMapper.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/dao/DispachRecognizeMapper.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/model/BatchBufferQueue.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/model/BufferQueue.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/producer/AlarmMessage.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/producer/KafkaProducerConfig.java, Cluster/Dispach-background/src/main/java/com/hzgc/cluster/dispach/producer/Producer.java, Cluster/Dispach-background/src/main/resources/application-dev.properties, Cluster/Dispach-background/src/main/resources/application-pro.properties, Cluster/Dispach-background/src/main/resources/mapping/DispachMapper.xml, Cluster/FaceCompare/Worker/bin/start-worker.sh
修改人： 伍家琦
修改内容：dispatch-background
合入人：赵喆
合入时间：2018-10-20
合入分支：2.4.0
=> dispatch-background

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/controller/DispatchController.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/DispatchService.java
修改人:邓紫阳
修改内容: 布控库新增,删除.修改 接口
修改模块: Dispatch
合入人:  邓紫阳
合入时间: 2018-10-20
合入分支: 2.4.0
=> 布控库添加:新增 删除 修改接口

Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispach/compare/CarCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispach/compare/FaceCompare.java, Cluster/FaceCompare/Master/bin/admin-master.sh, Cluster/FaceCompare/Master/src/main/java/com/hzgc/compare/command/RpcClientForMaster.java, Cluster/FaceCompare/Master/src/main/java/com/hzgc/compare/mem/TaskTracker.java, Cluster/FaceCompare/Master/src/main/java/com/hzgc/compare/server/MasterServer.java, Cluster/FaceCompare/Master/src/main/java/com/hzgc/compare/server/MasterServerImpl.java, Cluster/FaceCompare/Master/src/main/java/com/hzgc/compare/submit/JobSubmit.java, Cluster/FaceCompare/Worker/pom.xml, Cluster/FaceCompare/Worker/src/main/java/com/hzgc/compare/worker/conf/Config.java
修改人： 伍家琦
修改内容：Ip直接获取，faceCompare排除多余的包，master增加命令
修改模块：dispatch-background,facecompare
合入人：赵喆
合入时间：2018-10-23
合入分支：master
=> Ip直接获取，faceCompare排除多余的包，master增加命令

Service/People/bin/start-people.sh, Service/People/bin/stop-people.sh
修改人：闫森
修改模块;people
修改内容：脚本修改
合入人：赵喆
合入时间：2018-10-24
合入分支：2.3.0-rc1
=> people脚本修改

Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispach/compare/CarCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispach/compare/FaceCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispach/compare/MacCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispach/producer/AlarmMessage.java, Cluster/Dispatch-background/src/main/resources/mapping/DispachMapper.xml
修改人： 伍家琦
修改内容：重点人员布控增加消息字段
合入人：赵喆
合入时间：2018-10-26
合入分支：master
=> 重点人员布控增加消息字段

Common/Common-service/src/main/java/com/hzgc/common/service/api/service/PlatformService.java, Common/Common-service/src/main/java/com/hzgc/common/service/rest/BigDataPath.java, Service/Dispatch/pom.xml, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/Util/DispatchExcelUtils.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/controller/DispatchController.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/DispatchService.java
修改人：尹航
修改内容：布控库excel数据导入
修改模块：dispatch
合入人：赵喆
合入时间：2018-10-26
合入分支：master
=> dispatch excel import update

Common/Common-service/src/main/java/com/hzgc/common/service/api/service/PlatformService.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/DispatchService.java, Service/Dispatch/src/main/resources/application-dev.properties, Service/People/src/main/java/com/hzgc/service/people/service/PeopleService.java, Service/People/src/main/java/com/hzgc/service/util/PeopleExcelUtils.java, Service/People/src/main/resources/application-dev.properties
修改人：尹航
修改内容：修改 dispatch excel 导入 region 的判断方法和BUG，更新 people excel 导入方法
修改模块：dispatch, people
合入人：尹航
合入时间：2018-11-1
合入分支：master
=> people excel import update

Service/Dispatch/src/main/resources/application-pro.properties, Service/Fusion/docker/Dockerfile, Service/Fusion/docker/docker-entrypoint.sh, Service/Fusion/docker/make.sh, Service/Fusion/pom.xml, Service/Imsi-Dynrepo/bin/start-imsi-dynrepo.sh, Service/Imsi-Dynrepo/docker/Dockerfile, Service/Imsi-Dynrepo/docker/docker-entrypoint.sh, Service/Imsi-Dynrepo/docker/make.sh, Service/Imsi-Dynrepo/pom.xml, Service/Imsi-Dynrepo/src/main/resources/application-dev.properties, Service/People/docker/Dockerfile, Service/People/docker/docker-entrypoint.sh, Service/People/docker/make.sh, Service/People/pom.xml, Service/Person-Dynrepo/docker/Dockerfile, Service/Person-Dynrepo/docker/docker-entrypoint.sh, Service/Person-Dynrepo/docker/make.sh, Service/Person-Dynrepo/pom.xml, Service/Vehicle-Dynrepo/docker/Dockerfile, Service/Vehicle-Dynrepo/docker/docker-entrypoint.sh, Service/Vehicle-Dynrepo/docker/make.sh, Service/Vehicle-Dynrepo/pom.xml
修改人：闫森
修改内容：dockerfile
修改模块：service
合入人：赵喆
合入时间：2018-11-02
合入分支：docker-local
=> dockerfile

Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/dao/PictureMapper.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/InnerConsumer.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/MemeoryCache.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/mapping/PictureMapper.xml
修改人：雷禄辉
修改内容：修改比对实有人口添加
修改模块：PeopleManager-worker
合入人：赵喆
合入时间：2018-11-05
合入分支：2.3.0-rc1
=> 修改比对实有人口添加

Cluster/Dispatch-background/docker/Dockerfile, Cluster/Dispatch-background/docker/docker-entrypoint.sh, Cluster/Dispatch-background/docker/make.sh, Cluster/Dispatch-background/pom.xml
修改人：雷禄辉
修改内容：docker脚本添加
修改模块：Cluster/Dispatch-background
合入人：赵喆
合入时间：2018-11-05
合入分支：docker-local
=> docker脚本添加

Cluster/PeopleManager-background/PeopleManager-background-worker/bin/start-peoman-worker.sh, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/model/PeopleRecognize.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/PeopleCompare.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/application-dev.properties, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/application-pro.properties, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/mapping/PeopleRecognizeMapper.xml
修改人：雷禄辉
修改内容：比对增加数据重复过滤
修改模块：PeopleManager-worker
合入人：赵喆
合入时间：2018-11-06
合入分支：2.3.0-rc1
=> 比对增加数据重复过滤

Collect/src/main/java/com/hzgc/collect/bean/Base64Bean.java, Collect/src/main/java/com/hzgc/collect/controller/ExtractController.java, Collect/src/main/java/com/hzgc/collect/service/extract/FaceExtractService.java, Common/Common-service/src/main/java/com/hzgc/common/service/api/service/InnerService.java, Common/Common-service/src/main/java/com/hzgc/common/service/rest/BigDataPath.java
修改人：闫森
修改内容：增加行人车辆人脸的base64特征提取接口
修改模块：collect-ftp
合入人：赵喆
合入时间：2018-11-06
合入分支：master
=> 增加行人车辆人脸的base64特征提取接口

Deployment/project/bin/project-deploy.sh, Service/People/bin/start-people.sh
修改人：陈柯
修改内容：增加people模块启动脚本中的配置
修改模块：people
合入人：赵喆
合入时间：2018-11-07
合入分支：master
=> 增加people模块启动脚本中的配置

Cluster/Azkaban/bin/imsi_blacklist_table.sh, Cluster/Azkaban/bin/newpeople_table.sh, Cluster/Azkaban/bin/outpeople_table.sh
修改人：张宝霖
修改内容：修改azkaban定时任务
修改模块：Cluster
合入人：赵喆
合入时间：2018-11-08
合入分支：master
=> 修改azkaban定时任务

Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/cache/TableCache.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/CarCompareForLive.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/FaceCompareForLive.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/PersonCompareForLive.java
修改人： 伍家琦
修改内容：修改加载数据逻辑上的错误，解决活体布控告警重复发送的问题
合入人：赵喆
合入时间：2018-11-08
合入分支：master
=> 修改加载数据逻辑错误，解决活体布控重复告警问题

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/DispatchService.java
修改人:邓紫阳
修改内容:解决图片添加时逻辑问题
修改模块:dispatch
合入人:赵喆
合入时间:2018-11-08
合入分支:master
=> 修改布控照片提取特征值逻辑问题

Cluster/PeopleManager-background/PeopleManager-background-worker/bin/start-peoman-worker.sh, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/Application.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/dao/CarMapper.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/dao/CarRecognizeMapper.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/dao/PeopleMapper.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/model/Car.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/model/CarRecognize.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/model/People.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/CarConsumer.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/JobRunnerImpl.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/MessageMq.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/PeopleCompare.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/application-dev.properties, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/application-pro.properties, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/mapping/CarMapper.xml, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/mapping/CarRecognizeMapper.xml, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/mapping/PeopleMapper.xml, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/mapping/PeopleRecognizeMapper.xml, Cluster/PeopleManager-background/pom.xml
修改人：雷禄辉
修改内容：重点人员新增加字段及新增车辆比对
修改模块：PeopleManager-worker
合入人：赵喆
合入时间：2018-11-09
合入分支：master
=> 重点人员新增加字段及新增车辆比对

Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/cache/TableCache.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/consumer/KafkaComsumer.java
修改人： 伍家琦
修改内容：布控告警修改逻辑错误
合入人：赵喆
合入时间：2018-11-12
合入分支：master
=> 布控告警修改逻辑错误

Service/Dispatch/src/main/java/com/hzgc/service/alive/service/AliveService.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/controller/DispatchController.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/DispatchService.java, Service/Dispatch/src/main/java/com/hzgc/service/white/service/WhiteService.java
修改人:邓紫阳
修改内容:修改发送kafka
修改模块:Dispatch
合入人:赵喆
合入时间:2018-11-12
合入分支:master
=> 修改优化发送kafka相关参数

Cluster/PeopleManager-background/PeopleManager-background-worker/bin/start-peoman-worker.sh, Cluster/PeopleManager-background/PeopleManager-background-worker/docker/docker-entrypoint.sh, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/dao/PeopleMapper.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/CarConsumer.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/FaceConsumer.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/MessageMq.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cluster/peoman/worker/service/PeopleCompare.java, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/application-pro.properties, Cluster/PeopleManager-background/PeopleManager-background-worker/src/main/resources/mapping/PeopleMapper.xml
修改人：雷禄辉
修改内容：修改车辆比对及新增清晰度配置
修改模块：PeopleManager-worker
合入人：赵喆
合入时间：2018-11-13
合入分支：master
=> 修改车辆比对及新增清晰度配置

Cluster/Dispatch-background/bin/start-dispatch-background.sh, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/ConsumerFunction.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/CarCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/CarCompareForLive.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/FaceCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/FaceCompareForLive.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/FaceCompareForWhite.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/MacCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/PersonCompareForLive.java, Cluster/Dispatch-background/src/main/resources/application-dev.properties, Cluster/Dispatch-background/src/main/resources/application-pro.properties, Common/Common-service/src/main/java/com/hzgc/common/service/api/bean/CameraQueryDTO.java, Common/Common-service/src/main/java/com/hzgc/common/service/api/bean/DetectorQueryDTO.java
修改人： 伍家琦
修改内容：修改查询设备信息接口返回参数
合入人：赵喆
合入时间：2018-11-13
合入分支：master
=> 修改查询设备信息接口返回参数

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/controller/DispatchController.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/DispatchService.java, Service/Dispatch/src/main/java/com/hzgc/service/white/service/WhiteService.java
修改人:邓紫阳
修改内容:修改提取照片特征值提示日志
修改模块:Dispatch
合入人:赵喆
合入时间:2018-11-15
合入分支:master
=> 修改提取特征值报错提示

Distribution/src/assembly/assembly.xml
修改人：陈柯
修改内容：修改assembly文件
修改模块：Distribution
合入人：赵喆
合入时间：2018-11-15
合入分支：master
=> 修改assembly文件

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/DispatchService.java
修改人:邓紫阳
修改内容:黑名单修改接口新增判断
修改模块:Dispatch
合入人:赵喆
合入时间:2018-11-16
合入分支:master
=> 修改布控(黑名单)修改照片问题

Cluster/Azkaban/bin/24hour_count_table.sh, Cluster/Azkaban/bin/device_recogize_table.sh, Cluster/Azkaban/bin/newpeople_table.sh, Deployment/normal/project/sql/peopleDatabase.sql
修改人：张宝霖
修改内容：修改建表语句和定时sql
修改模块：Deployment&Cluster
合入人：赵喆
合入时间：2018-11-16
合入分支：master
=> 修改建表语句和定时sql

Deployment/local/docker-compose/docker-compose.yml
修改人：陈柯
修改内容：修改docker-compose文件
修改模块：Depolyment
合入人：赵喆
合入时间：2018-11-17
合入分支：master
=> 修改docker-compose文件

Service/Dispatch/src/main/java/com/hzgc/service/dispatch/param/DispatchVO.java, Service/Dispatch/src/main/java/com/hzgc/service/dispatch/service/DispatchService.java, Service/Dispatch/src/main/resources/application-dev.properties, Service/Dispatch/src/main/resources/mapping/DispatchMapper.xml
修改人：尹航
修改内容：模糊查询返回字段修改，判断是否有照片
修改模块：dispatch
合入人：赵喆
合入时间：2018-11-19
合入分支：master
=> dispatch模块修改

Deployment/local/docker-compose-service/docker-compose.yml
修改人：陈柯
修改内容：修改docker-compose文件
合入人：赵喆
合入时间：2018-11-20
合入分支：master
=> 修改jenkins打包

Common/Common-service/src/main/java/com/hzgc/common/service/rest/BigDataPath.java, Service/Dispatch/src/main/resources/application-dev.properties, Service/People/src/main/java/com/hzgc/service/community/dao/NewPeopleMapper.java, Service/People/src/main/java/com/hzgc/service/community/dao/OutPeopleMapper.java, Service/People/src/main/java/com/hzgc/service/community/dao/RecognizeRecordMapper.java, Service/People/src/main/java/com/hzgc/service/people/controller/PeopleController.java, Service/People/src/main/java/com/hzgc/service/people/dao/CarMapper.java, Service/People/src/main/java/com/hzgc/service/people/dao/FlagMapper.java, Service/People/src/main/java/com/hzgc/service/people/dao/HouseMapper.java, Service/People/src/main/java/com/hzgc/service/people/dao/ImsiMapper.java, Service/People/src/main/java/com/hzgc/service/people/dao/PhoneMapper.java, Service/People/src/main/java/com/hzgc/service/people/dao/PictureMapper.java, Service/People/src/main/java/com/hzgc/service/people/service/PeopleService.java, Service/People/src/main/resources/community-mapping/NewPeopleMapper.xml, Service/People/src/main/resources/community-mapping/OutPeopleMapper.xml, Service/People/src/main/resources/community-mapping/RecognizeRecordMapper.xml, Service/People/src/main/resources/people-mapping/CarMapper.xml, Service/People/src/main/resources/people-mapping/FlagMapper.xml, Service/People/src/main/resources/people-mapping/HouseMapper.xml, Service/People/src/main/resources/people-mapping/ImsiMapper.xml, Service/People/src/main/resources/people-mapping/PhoneMapper.xml, Service/People/src/main/resources/people-mapping/PictureMapper.xml
修改人:邓紫阳
修改内容:新增删除接口
修改模块:People
合入人:赵喆
合入时间:2018-11-20
合入分支:master
=> 人口库新增删除功能(删除单个人口全部信息)

Cluster/Spark/docker/start-kafka-to-parquet.sh, Deployment/local/docker-compose-modeule/docker-compose.yml, Deployment/local/docker-compose-service/docker-compose.yml, Service/Imsi-Dynrepo/docker/docker-entrypoint.sh
修改人：陈柯
修改内容：修改local模式bug
合入人：赵喆
合入时间：2018-11-20
合入分支：master
=> 修改local模式bug

Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/CarCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/FaceCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/FaceCompareForWhite.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/compare/MacCompare.java, Cluster/Dispatch-background/src/main/java/com/hzgc/cluster/dispatch/consumer/KafkaComsumer.java, Cluster/FaceCompare/Worker/src/main/java/com/hzgc/compare/worker/persistence/ElasticSearchClient.java, Cluster/FaceCompare/Worker/src/main/resources/worker.properties, Common/Common-collect/src/main/java/com/hzgc/common/collect/bean/MacObject.java
修改人： 伍家琦
修改内容：修改dispatch-background
合入人：赵喆
合入时间：2018-11-21
合入分支：master
=> 修改dispatch-background

Service/People/src/main/resources/community-mapping/RecognizeRecordMapper.xml
bug修复：
1，重点人员识别记录出现重复数据
2，重点人员告警展示（大数据可视化首页左下角）出现重复数据
=> bug修复：重点人员告警展示（大数据可视化首页左下角），重点人员识别记录：出现重复数据，

Deployment/normal/project/sql/peopleDatabase.sql, Service/People/src/main/java/com/hzgc/service/community/param/ImportantPeopleRecognizeVO.java, Service/People/src/main/java/com/hzgc/service/community/service/CommunityService.java, Service/People/src/main/java/com/hzgc/service/people/controller/PeopleController.java, Service/People/src/main/java/com/hzgc/service/people/param/Flag.java, Service/People/src/main/java/com/hzgc/service/people/param/PeopleVO.java, Service/People/src/main/java/com/hzgc/service/people/param/SearchPeopleDTO.java, Service/People/src/main/java/com/hzgc/service/people/service/PeopleService.java, Service/People/src/main/resources/application-dev.properties, Service/People/src/main/resources/people-mapping/PeopleMapper.xml
修改人:尹航
修改内容:人口库检索增加标签筛选、人口库根据ID查询人口信息修改Flag、重点人员识别记录查询修改Flag
修改模块:people
合入人:赵喆
合入时间:2018-11-27
合入分支:master
=> 关于 flag 检索等更新

Collect/docker/docker-entrypoint.sh, Deployment/normal/project/sql/peopleDatabase.sql
修改人：陈柯
修改内容：sql以及properties文件
修改模块：ftp以及Deployment
合入人：赵喆
合入时间：2018/12/11
合入分支：master
=> modify the bug

Cloud-Platform/Fusion/pom.xml
修改人:尹航
修改内容:fusion pom修改
修改模块:fusion
合入人:赵喆
合入时间:2018-12-15
合入分支:2.4.0
=> fusion pom

Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/pom.xml, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cloud/peoman/worker/Application.java, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cloud/peoman/worker/service/LoadDataFromTiDB.java, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cloud/peoman/worker/service/PeopleCompare.java, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cloud/peoman/worker/service/People_background_table.java, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/resources/application-dev.properties, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/resources/application-pro.properties, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/resources/log4j.properties, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/resources/mapping/RecognizeRecordMapper.xml
修改人：雷禄辉
修改内容：peoman-worker的修改
修改模块：peoman-worker
合入人：赵喆
合入时间：2018-12-19
合入分支：2.4.0
=> peoman-worker的修改

Analysis-Platform/Dispatch-background/pom.xml, Analysis-Platform/Dispatch/pom.xml, Analysis-Platform/Dispatch/src/main/resources/application-pro.properties, Deployment/local/docker-compose/analysis/basis/docker-compose.yml, Deployment/local/docker-compose/cloud/docker-compose.yml, Deployment/normal/docker-compose/analysis/basis/docker-compose.yml, Deployment/normal/docker-compose/analysis/dispatch/docker-compose.yml, Deployment/normal/docker-compose/analysis/search/docker-compose.yml, Deployment/normal/docker-compose/cloud/fusion/docker-compose.yml, Deployment/normal/docker-compose/cloud/imsi/docker-compose.yml, Deployment/normal/docker-compose/cloud/peoman/docker-compose.yml, Deployment/normal/docker-compose/cloud/people/docker-compose.yml
修改人：闫森
修改内容：docker-compose日志控制台打印
修改模块：local,normal
合入人：赵喆
合入时间：2018-12-21
合入分支：2.4.0
=> docker-compose日志控制台打印

Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cloud/peoman/worker/service/FaceConsumer.java, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cloud/peoman/worker/service/InnerConsumer.java, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/java/com/hzgc/cloud/peoman/worker/service/JobRunnerImpl.java, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/resources/application-dev.properties, Cloud-Platform/PeopleManager-background/PeopleManager-background-worker/src/main/resources/application-pro.properties
修改人：雷禄辉
修改内容：比对修改为加载所有底库数据
修改模块：peoman-worker
合入人：赵喆
合入时间：2018-12-25
合入分支：2.4.0
=> 比对修改为加载所有底库数据

Deployment/normal/module-ansible/bootstrap.sh, Deployment/normal/module-ansible/hosts
修改人：陈柯
修改内容：修改bootstrap脚本以及hosts文件
合入人：赵喆
合入时间：2018/12/28
合入分支：2.4.0
=> modify the bootstrap.sh

Analysis-Platform/Es-vector-score/pom.xml, Analysis-Platform/Es-vector-score/src/main/assemblies/plugin.xml, Analysis-Platform/Es-vector-score/src/main/java/com/hzgc/elasticsearch/Util.java, Analysis-Platform/Es-vector-score/src/main/java/com/hzgc/elasticsearch/plugin/VectorScoringPlugin.java, Analysis-Platform/Es-vector-score/src/main/java/com/hzgc/elasticsearch/script/VectorScoreScript.java, Analysis-Platform/Es-vector-score/src/main/java/com/hzgc/elasticsearch/service/VectorScoringScriptEngineService.java, Analysis-Platform/Es-vector-score/src/main/resources/license-check/license_header_definition.xml, Analysis-Platform/Es-vector-score/src/main/resources/license-check/vector_scoring_license_header.txt, Analysis-Platform/Es-vector-score/src/main/resources/plugin-descriptor.properties, Analysis-Platform/Face-Dynrepo/src/main/java/com/hzgc/cloud/dynrepo/controller/CaptureSearchController.java, Analysis-Platform/Face-Dynrepo/src/main/java/com/hzgc/cloud/dynrepo/dao/ElasticSearchDao.java, Analysis-Platform/Face-Dynrepo/src/main/java/com/hzgc/cloud/dynrepo/dao/FaceCompareClient.java, Analysis-Platform/Face-Dynrepo/src/main/java/com/hzgc/cloud/dynrepo/service/CaptureSearchService.java, Analysis-Platform/Face-Dynrepo/src/main/java/com/hzgc/cloud/dynrepo/service/CaptureServiceHelper.java, Analysis-Platform/pom.xml
修改人： 伍家琦
修改内容：es插件和人脸动态库意图搜图接口
修改模块：es-vector-score
合入人：赵喆
合入时间：2018-12-28
合入分支：es-vector-score
=> es插件和人脸动态库意图搜图接口

Analysis-Platform/Face-Dynrepo/src/main/java/com/hzgc/cloud/dynrepo/dao/FaceCompareClient.java
修改人： 伍家琦
修改内容：解决没有返回值时空指针异常
修改模块：face-dynrepo
合入人：赵喆
合入时间：2018-12-29
合入分支：es-vector-score
=> 解决没有返回值时空指针异常
